import pandas as pd
import pyautogui as py
import clipboard
from time import sleep
import pyperclip

for c in range(128):
    sleep(3.5)
    py.click(1365,411)
    sleep(4)
    py.doubleClick(303,461)
    sleep(4)
    py.click(725,540)
    sleep(4)
    py.moveTo(762,187)
    sleep(1)
    py.mouseDown()
    sleep(1)
    py.moveTo(1059,288)
    sleep(2)
    py.mouseUp()
    sleep(1)
    pyperclip.copy('')
    py.hotkey('ctrl','c')
    sleep(1)
    select = clipboard.paste()

    if 'Select' in select:
        py.click(896,861)
        sleep(6)
        py.doubleClick(785,362)
        pyperclip.copy('')
        py.hotkey('ctrl', 'c')
        sleep(1)
        press = clipboard.paste()
        if 'Press' in press or 'please' in press:
            py.press('f5')
            sleep(7)
            py.click(1365, 411)
            sleep(4)
            py.doubleClick(303,461)
            sleep(4)
            py.click(725, 540)
            sleep(4)
            py.moveTo(762, 187)
            sleep(1)
            py.mouseDown()
            sleep(1)
            py.moveTo(1059, 288)
            sleep(2)
            py.mouseUp()
            sleep(1)
            pyperclip.copy('')
            py.hotkey('ctrl', 'c')
            sleep(1)
            select = clipboard.paste()
            if 'Select' in select:
                py.click(896, 861)
                sleep(6)
                py.doubleClick(785, 362)
                pyperclip.copy('')
                py.hotkey('ctrl', 'c')
                sleep(1)
                press = clipboard.paste()


        else:
            py.click(725, 540)
            sleep(4)
            py.click(892, 636)
            sleep(5)
            py.doubleClick(785, 362)
            pyperclip.copy('')
            py.hotkey('ctrl', 'c')
            sleep(1)
            press = clipboard.paste()
            if 'Press' in press or 'please' in press:
                py.press('f5')
                sleep(4)
                py.click(1365, 411)
                sleep(4)
                py.doubleClick(303, 461)
                sleep(4)
                py.click(725, 540)
                sleep(4)
                py.moveTo(762, 187)
                sleep(1)
                py.mouseDown()
                sleep(1)
                py.moveTo(1059, 288)
                sleep(2)
                py.mouseUp()
                sleep(1)
                pyperclip.copy('')
                py.hotkey('ctrl', 'c')
                sleep(1)
                select = clipboard.paste()
                if 'Select' in select:
                    py.click(896, 861)
                    sleep(6)
                    py.doubleClick(785, 362)
                    pyperclip.copy('')
                    py.hotkey('ctrl', 'c')
                    sleep(1)
                    press = clipboard.paste()
    elif 'Select' not in select:
        py.click(725, 540)
        sleep(4)
        py.click(892, 636)
        sleep(5)
        py.doubleClick(785, 362)
        pyperclip.copy('')
        py.hotkey('ctrl', 'c')
        sleep(1)
        press = clipboard.paste()
        if 'Press' in press or 'please' in press:
            py.press('f5')
            sleep(4)
            py.click(1365, 411)
            sleep(4)
            py.doubleClick(303,461)
            sleep(4)
            py.click(725, 540)
            sleep(4)
            py.moveTo(762, 187)
            sleep(1)
            py.mouseDown()
            sleep(1)
            py.moveTo(1059, 288)
            sleep(2)
            py.mouseUp()
            sleep(1)
            pyperclip.copy('')
            py.hotkey('ctrl', 'c')
            sleep(1)
            select = clipboard.paste()
            if 'Select' in select:
                py.click(896, 861)
                sleep(6)
                py.doubleClick(785, 362)
                pyperclip.copy('')
                py.hotkey('ctrl', 'c')
                sleep(1)
                press = clipboard.paste()



        py.click(1057, 632)
        sleep(5)
    py.click(1057,632)
    sleep(5)
    py.moveTo(173,864)
    sleep(1)
    py.mouseDown()
    sleep(1)
    py.moveTo(1612,1038)
    sleep(2)
    py.moveTo(1671,927)
    sleep(1)
    py.mouseUp()
    py.hotkey('ctrl','c')
    sleep(1)
    py.click(880,1052)
    sleep(3)
    py.press('esc')
    sleep(2)
    py.press('down')
    sleep(1)
    py.hotkey('ctrl','up')
    sleep(1)
    py.press('down')
    sleep(1)
    py.hotkey('ctrl','v')
    sleep(2)
    py.hotkey('ctrl','down')
    sleep(2)
    py.press('down')
    sleep(2)
    py.click(929,1051)
    sleep(2)
    py.click(970,76)
    sleep(2)
    py.click(1424,20)
    sleep(2)
    py.click(829,1057)
    sleep(2)
    py.press('f5')
    sleep(3)
    py.click(1234,312)